### ISSUE TITLE
Cindy's Review of Josh's Blog

### ISSUE THREAD

**Issue by cindyytong** [JDe-Lora/microBlogRefactor#1]
Nice blog! Here are some tips on improvements:

1. Fix top margin so that the blue border surrounds the entire perimeter of the white content space
2. The default text in the form "Type in Nonnsense(":
a. gets cut off
b. the text that gets typed in should get removed when it is pushed to the bottom upon each submission (click on the submit button)
c. center align the blog posts that get pushed to the bottom (it should be a little more left)
3. In local storage, the buttonClick is not updating past the value of 1, you don't necessarily need to update this since you are not calling the value of button clicks but you could update your js file so that the buttonclick gets updated with the correct value
4. app.js on line 14, to make it shorter you could do $('<li>') instead of appending an entire string

These are tips! It looks great.

C

**Comment by JDe-Lora** [comment]
Thank you!
